defaults:
  - base_config
  - data: baseline
  - harmonization: default
  - model: default
  - _self_

debug: False
# data_dir: /home/bily/ETH/ask-volk/data/
# model_dir: /home/bily/ETH/ask-volk/models/
data_dir: /work/ask-volk/data/
model_dir: /work/ask-volk/models/
